import { Award, BookOpenCheck, HeartHandshake, Lightbulb, Target, UsersRound } from "lucide-react";
import { LocalizedText } from "@/components/language-provider";
import { PageIntro } from "@/components/public/page-intro";

const values = [
  [Target, "Purposeful learning", "उद्देश्यपूर्ण सिकाइ", "We teach for understanding, not only examination results.", "हामी केवल परीक्षाको नतिजाका लागि होइन, बुझाइका लागि पढाउँछौँ।"],
  [HeartHandshake, "Respect & care", "सम्मान र हेरचाह", "Every learner is known, heard and encouraged.", "हरेक विद्यार्थीलाई चिनिन्छ, सुनिन्छ र प्रोत्साहित गरिन्छ।"],
  [Award, "High standards", "उच्च मापदण्ड", "Ambition is paired with support and honest effort.", "महत्त्वाकाङ्क्षालाई सहयोग र इमानदार प्रयाससँग जोड्छौँ।"],
] as const;

export default function AboutPage() { return <><PageIntro eyebrow="OUR SCHOOL" titleEn="A school with heart and direction." titleNe="हृदय र दिशा भएको विद्यालय।" copyEn="For three decades, Bhanubhakta has served families in Morang with a grounded, forward-looking education." copyNe="तीन दशकदेखि भानुभक्तले मोरङका परिवारलाई जीवनसँग जोडिएको र भविष्य उन्मुख शिक्षा दिँदै आएको छ।"/><section className="content-section"><div className="container about-story"><div className="about-photo-collage"><img className="about-photo-main" src="/images/check3.png" alt="Teacher leading a lesson"/><img className="about-photo-detail" src="/images/check4.png" alt="Students learning together"/><div className="about-years"><strong>30</strong><span>Years of<br/>learning</span></div></div><div className="prose about-copy"><p className="eyebrow">OUR STORY</p><LocalizedText as="h2" en="Grounded in community. Focused on every child." ne="समुदायमा जोडिएको। हरेक बालबालिकामा केन्द्रित।"/><LocalizedText as="p" en="Bhanubhakta Secondary School began in 1995 with a simple conviction: quality education should be accessible, humane and rooted in community. What started as a small group of committed educators has become a vibrant learning home for students from early years to higher secondary level." ne="भानुभक्त माध्यमिक विद्यालय १९९५ मा एउटा सरल विश्वासका साथ सुरु भएको थियो—गुणस्तरीय शिक्षा पहुँचयोग्य, मानवीय र समुदायसँग जोडिएको हुनुपर्छ। समर्पित शिक्षकहरूको सानो समूहबाट सुरु भएको यो विद्यालय आज प्रारम्भिक कक्षादेखि उच्च माध्यमिक तहसम्मका विद्यार्थीको जीवन्त सिकाइ घर बनेको छ।"/><div className="about-pill-row"><span><UsersRound size={17}/> Community first</span><span><BookOpenCheck size={17}/> Learning always</span></div></div></div></section><section className="about-mission-section"><div className="container mission-grid"><article className="mission-card"><Lightbulb size={31}/><p className="eyebrow">MISSION</p><LocalizedText as="h2" en="Curious, capable, compassionate." ne="जिज्ञासु, सक्षम र संवेदनशील।"/><LocalizedText as="p" en="We cultivate informed learners through an inclusive academic culture where every voice and aspiration matters." ne="हरेक आवाज र आकांक्षाको महत्त्व हुने समावेशी शैक्षिक संस्कृतिमार्फत हामी सूचित विद्यार्थी तयार गर्छौँ।"/></article><article className="mission-visual"><img src="/images/check5.png" alt="Students collaborating"/><div><span>OUR VISION</span><p>A generation ready to shape a better Nepal.</p></div></article></div></section><section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">WHAT GUIDES US</p><LocalizedText as="h2" en="Values we live by" ne="हाम्रा मार्गदर्शक मूल्यहरू"/></div></div><div className="value-grid">{values.map(([Icon, en, ne, copyEn, copyNe]) => <article className="value-card" key={en}><div className="value-icon"><Icon size={25}/></div><LocalizedText as="h3" en={en} ne={ne}/><LocalizedText as="p" en={copyEn} ne={copyNe}/></article>)}</div></div></section></>; }
