"use client";

import Link from "next/link";
import { CalendarDays, CheckCircle2, FileText, Image, Images, Plus, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { createClient, hasSupabaseConfig } from "@/lib/supabase/client";

type Counts = { notices: number; staffs: number; hero_slides: number; events: number };
type Activity = { label: string; detail: string; date: string; href: string; icon: "notice" | "event" };
const initial: Counts = { notices: 0, staffs: 0, hero_slides: 0, events: 0 };

export function AdminOverview() {
  const [counts, setCounts] = useState(initial); const [activity, setActivity] = useState<Activity[]>([]);
  useEffect(() => { const supabase = createClient(); if (!supabase) return; Promise.all(["notices", "staffs", "hero_slides", "events"].map(async (table) => [table, (await supabase.from(table).select("id", { count: "exact", head: true })).count || 0] as const)).then((rows) => setCounts(Object.fromEntries(rows) as Counts)); Promise.all([supabase.from("notices").select("id,title_en,title_ne,date_published").order("date_published", { ascending: false }).limit(3), supabase.from("events").select("id,title_en,title_ne,event_date").order("event_date", { ascending: false }).limit(3)]).then(([notices, events]) => { const items: Activity[] = [...(notices.data || []).map((item) => ({ label: item.title_en || item.title_ne, detail: "Notice published", date: item.date_published, href: "/admin/dashboard/notices", icon: "notice" as const })), ...(events.data || []).map((item) => ({ label: item.title_en || item.title_ne, detail: "Event scheduled", date: item.event_date, href: "/admin/dashboard/events", icon: "event" as const }))].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 5); setActivity(items); }); }, []);
  if (!hasSupabaseConfig) return <div className="setup-card">This dashboard becomes live after Supabase is configured. Follow <code>SUPABASE_SETUP.md</code> in the project root, then return here.</div>;
  const cards = [["Published notices", counts.notices, FileText], ["Staff members", counts.staffs, Users], ["Hero photos", counts.hero_slides, Images], ["Events", counts.events, CalendarDays]] as const;
  const health = [{ label: "Notice board", ready: counts.notices > 0 }, { label: "Staff directory", ready: counts.staffs > 0 }, { label: "Homepage gallery", ready: counts.hero_slides > 0 }, { label: "Events page", ready: counts.events > 0 }];
  return <div className="overview-content"><div className="dashboard-stats">{cards.map(([label, value, Icon]) => <article className="dashboard-stat" key={label}><span className="dashboard-stat-icon"><Icon size={19}/></span><p>{label}</p><div>{value}</div></article>)}</div><div className="overview-grid"><section className="admin-panel activity-panel"><div className="admin-panel-header"><div><h2>Recent activity</h2><p>Your latest public website updates.</p></div></div>{activity.length ? <div className="activity-list">{activity.map((item) => <Link href={item.href} className="activity-item" key={`${item.icon}-${item.label}`}><span className="activity-icon">{item.icon === "notice" ? <FileText size={16}/> : <CalendarDays size={16}/>}</span><span><strong>{item.label}</strong><small>{item.detail} · {new Date(item.date).toLocaleDateString("en-GB", { day: "numeric", month: "short" })}</small></span></Link>)}</div> : <p className="empty-state">No content activity yet.</p>}</section><section className="admin-panel health-panel"><div className="admin-panel-header"><div><h2>Content health</h2><p>Quick check of your public sections.</p></div></div><div className="health-list">{health.map((item) => <div key={item.label}><span>{item.label}</span><strong className={item.ready ? "ready" : "missing"}>{item.ready ? <><CheckCircle2 size={15}/>Live</> : "Needs content"}</strong></div>)}</div></section></div><section className="admin-panel quick-actions"><div><h2>Quick actions</h2><p>Keep your website fresh with a few clicks.</p></div><div><Link className="btn" href="/admin/dashboard/notices"><Plus size={16}/>Add notice</Link><Link className="btn secondary" href="/admin/dashboard/events"><CalendarDays size={16}/>Add event</Link><Link className="btn secondary" href="/admin/dashboard/hero"><Image size={16}/>Update slider</Link></div></section></div>;
}
