/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { LoaderCircle, Pencil, Plus, Trash2, Upload, X } from "lucide-react";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { ImageCropper } from "@/components/admin/image-cropper";
import { createClient, hasSupabaseConfig } from "@/lib/supabase/client";

type RecordRow = Record<string, string | number | null | undefined> & { id: string };
type Field = { name: string; label: string; type?: "text" | "date" | "number" | "textarea" | "email" };

export function RecordManager({ table, title, description, fields, initialRows, assetField }: { table: string; title: string; description: string; fields: Field[]; initialRows: RecordRow[]; assetField?: string }) {
  const [rows,setRows]=useState<RecordRow[]>(initialRows); const [draft,setDraft]=useState<Record<string,string>>({}); const [editing,setEditing]=useState<RecordRow | null>(null); const [modal,setModal]=useState(false); const [asset,setAsset]=useState<File | null>(null); const [message,setMessage]=useState(""); const [pending,setPending]=useState(false);
  useEffect(()=>{const client=createClient(); if(!client)return; (client.from as any)(table).select("*").order("created_at",{ascending:false}).then(({data,error}:{data:RecordRow[]|null;error:Error|null})=>{if(error)setMessage(error.message);else setRows(data || []);});},[table]);
  function openNew(){setEditing(null);setAsset(null);setDraft(Object.fromEntries(fields.map(field=>[field.name,field.type==="number"?"0":""])));setMessage("");setModal(true);}
  function openEdit(row:RecordRow){setEditing(row);setAsset(null);setDraft(Object.fromEntries(fields.map(field=>[field.name,String(row[field.name] ?? "")]))) ;setMessage("");setModal(true);}
  function update(name:string,value:string){setDraft(current=>({...current,[name]:value}));}
  async function uploadAsset(client: NonNullable<ReturnType<typeof createClient>>) { if(!asset || !assetField) return draft[assetField || ""]; const filename=`${table}/${Date.now()}-${asset.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`; const {error}=await client.storage.from("school-media").upload(filename,asset,{upsert:false}); if(error) throw error; const {data}=client.storage.from("school-media").getPublicUrl(filename); return data.publicUrl; }
  async function save(event:FormEvent){event.preventDefault();const client=createClient();if(!client)return;setMessage("");const suppliedAssetUrl=assetField?draft[assetField]?.trim():"";if(assetField&&!asset&&!suppliedAssetUrl){setMessage("Select and crop an image, or enter a valid image URL before saving.");return;}setPending(true);try{const values:Record<string,string|number>={...draft};fields.filter(field=>field.type==="number").forEach(field=>values[field.name]=Number(draft[field.name]||0));if(assetField){const url=await uploadAsset(client);if(url)values[assetField]=url;if(!String(values[assetField]||"").trim())throw new Error("An image is required. Select an image and choose ‘Crop & use image’ before saving.");}let result; if(editing) result=await (client.from as any)(table).update(values).eq("id",editing.id).select().single(); else result=await (client.from as any)(table).insert(values).select().single(); if(result.error)throw result.error;setRows(current=>editing?current.map(row=>row.id===editing.id?result.data:row):[result.data,...current]);setModal(false);}catch(error){setMessage(error instanceof Error?error.message:"Could not save this record.");}finally{setPending(false);}}
  async function remove(row:RecordRow){if(!confirm("Delete this record? This cannot be undone."))return;const client=createClient();if(!client)return;const {error}=await (client.from as any)(table).delete().eq("id",row.id);if(error){setMessage(error.message);return;}setRows(current=>current.filter(item=>item.id!==row.id));}
  const cropAspect = table === "staffs" ? 3 / 4 : table === "hero_slides" ? 16 / 7 : 4 / 3;
  if(!hasSupabaseConfig)return <div className="setup-card"><strong>{title} is ready to connect.</strong><br/>Add the Supabase environment variables and run the supplied SQL setup. Records will then be created, edited and deleted directly in your database.</div>;
  return <><div className="admin-panel"><div className="admin-panel-header"><div><h2>{title}</h2><p style={{color:"#62728a",fontSize:".88rem",margin:"6px 0 0"}}>{description}</p></div><button className="btn" onClick={openNew}><Plus size={16}/>Add new</button></div>{message && <p className="form-error">{message}</p>}<table className="admin-table"><thead><tr>{fields.slice(0,3).map(field=><th key={field.name}>{field.label}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{fields.slice(0,3).map(field=><td key={field.name}>{assetField===field.name && row[field.name]?<a href={String(row[field.name])} target="_blank" rel="noreferrer">Open file</a>:String(row[field.name]||"—")}</td>)}<td><div className="admin-actions"><button className="outline-button" onClick={()=>openEdit(row)}><Pencil size={13}/> Edit</button><button className="danger-button" onClick={()=>remove(row)}><Trash2 size={13}/> Delete</button></div></td></tr>)}{rows.length===0&&<tr><td colSpan={4} style={{textAlign:"center",color:"#62728a",padding:25}}>No records yet.</td></tr>}</tbody></table></div>{modal&&<div className="modal-backdrop" role="dialog" aria-modal="true"><form className="modal" onSubmit={save}><div className="modal-header"><h2>{editing?"Edit":"Add"} {title.replace(/s$/,'')}</h2><button type="button" onClick={()=>setModal(false)} aria-label="Close"><X/></button></div><div className="admin-form">{fields.map(field=><label className={field.type==="textarea"?"form-label full":"form-label"} key={field.name}>{field.label}{field.type==="textarea"?<textarea className="field" value={draft[field.name]||""} onChange={e=>update(field.name,e.target.value)}/>:<input required={!["title_en","description_ne","description_en","image_url","photo_url","pdf_url"].includes(field.name)} className="field" type={field.type||"text"} value={draft[field.name]||""} onChange={e=>update(field.name,e.target.value)}/>}</label>)}{assetField && (assetField.includes("pdf") ? <label className="form-label full">Upload PDF (optional)<span className="field" style={{display:"flex",alignItems:"center",gap:9}}><Upload size={16}/><input type="file" accept="application/pdf" onChange={(event:ChangeEvent<HTMLInputElement>)=>setAsset(event.target.files?.[0]||null)}/></span></label> : <div className="form-label full"><span>Crop image before upload</span><ImageCropper aspect={cropAspect} onCropped={setAsset}/>{asset && <small className="crop-file-selected">Ready: {asset.name}</small>}<small style={{color:"#62728a",fontWeight:400}}>Choose an image, adjust its crop, then select <strong>Crop & use image</strong> before saving.</small></div>)}{message&&<p className="form-error full">{message}</p>}<button className="btn" disabled={pending}>{pending&&<LoaderCircle size={16} className="animate-spin"/>}{editing?"Save changes":"Create record"}</button></div></form></div>}</>;
}




